-- ------------------------------------------------------------
-- Table: orderm
-- Fix: `tdate` date NOT NULL DEFAULT NULL  →  NOT NULL removed
--      A NOT NULL column cannot have DEFAULT NULL — contradiction
-- ------------------------------------------------------------

CREATE TABLE `orderm` (
  `slno`        decimal(10,0)  NOT NULL,
  `ordno`       char(10)       NOT NULL,
  `tdate`       date           NOT NULL,
  `custcode`    char(8)        DEFAULT NULL,
  `custname`    varchar(30)    DEFAULT NULL,
  `duedate`     date           DEFAULT NULL,
  `rate`        decimal(8,2)   DEFAULT 0.00,
  `billamt`     decimal(10,2)  DEFAULT 0.00,
  `eamt`        decimal(10,2)  DEFAULT 0.00,
  `advance`     decimal(10,2)  DEFAULT 0.00,
  `status`      smallint(6)    DEFAULT 1,
  `control`     smallint(6)    DEFAULT 1,
  `salebill`    varchar(10)    DEFAULT NULL,
  `smcode`      char(8)        DEFAULT NULL,
  `gadvance`    decimal(8,3)   DEFAULT 0.000,
  `sretamt`     decimal(10,2)  DEFAULT NULL,
  `ichadv`      smallint(6)    DEFAULT NULL,
  `iexadv`      smallint(6)    DEFAULT NULL,
  `isradv`      smallint(6)    DEFAULT NULL,
  `ob`          decimal(10,2)  DEFAULT NULL,
  `addr`        varchar(60)    DEFAULT NULL,
  `refund`      decimal(9,2)   DEFAULT NULL,
  `closed`      smallint(6)    DEFAULT NULL,
  `jewlcode`    char(10)       DEFAULT NULL,
  `duedate_org` date           DEFAULT NULL,
  `ic`          varchar(5)     DEFAULT NULL,
  `phone`       varchar(20)    DEFAULT NULL,
  `tax`         decimal(8,2)   DEFAULT NULL,
  `note`        varchar(40)    DEFAULT NULL,
  `amttowgt`    char(1)        DEFAULT NULL,
  `blocked`     varchar(1)     DEFAULT NULL,
  `counter`     varchar(10)    DEFAULT NULL,
  `taxable`     char(1)        DEFAULT NULL,
  `cbcode`      varchar(10)    DEFAULT NULL,
  `bcharge`     decimal(8,2)   DEFAULT NULL,
  `addbcharge`  char(1)        DEFAULT NULL,
  `ccamt`       decimal(10,2)  DEFAULT NULL,
  `chqno`       varchar(20)    DEFAULT NULL,
  `chqdate`     date           DEFAULT NULL,
  `chqamt`      decimal(12,2)  DEFAULT NULL,
  `chqbank`     varchar(10)    DEFAULT NULL,
  `chqpdc`      char(1)        DEFAULT NULL,
  `cocode`      varchar(10)    DEFAULT NULL,
  `cadvslno`    decimal(10,0)  DEFAULT NULL,
  `badvslno`    decimal(10,0)  DEFAULT NULL,
  `pan`         varchar(20)    DEFAULT NULL,
  `ppno`        varchar(15)    DEFAULT NULL,
  `nationality` varchar(20)    DEFAULT NULL,
  `dob`         date           DEFAULT NULL,
  `resident`    varchar(2)     DEFAULT NULL,
  `tin`         varchar(15)    DEFAULT NULL,
  `sdate`       date           DEFAULT NULL,
  `rate18`      decimal(8,2)   DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
