-- ------------------------------------------------------------
-- Table: purchasem
-- Fix: `ttime` time DEFAULT curtime()  →  DEFAULT NULL
--      curtime() as column default requires MySQL 8.0.13+
--      On MySQL 5.7 / MariaDB this causes a #1067 syntax error
-- ------------------------------------------------------------

CREATE TABLE `purchasem` (
  `slno`        decimal(10,0)  NOT NULL,
  `tdate`       date           DEFAULT NULL,
  `ttime`       time           DEFAULT NULL,
  `billno`      char(20)       DEFAULT NULL,
  `docno`       char(10)       DEFAULT NULL,
  `suppcode`    char(8)        DEFAULT NULL,
  `name`        varchar(30)    DEFAULT NULL,
  `billamt`     decimal(10,2)  DEFAULT 0.00,
  `pamt`        decimal(10,2)  DEFAULT 0.00,
  `addamt`      decimal(10,2)  DEFAULT 0.00,
  `status`      smallint(6)    DEFAULT 0,
  `pr`          char(1)        DEFAULT NULL,
  `eamt`        decimal(10,2)  DEFAULT 0.00,
  `duedate`     date           DEFAULT NULL,
  `pamtafter`   decimal(10,2)  DEFAULT 0.00,
  `control`     smallint(6)    DEFAULT 1,
  `rate`        decimal(9,2)   DEFAULT 0.00,
  `smcode`      char(10)       DEFAULT NULL,
  `round`       decimal(5,2)   DEFAULT NULL,
  `netamt`      decimal(10,2)  DEFAULT NULL,
  `taxamt`      decimal(10,2)  DEFAULT NULL,
  `ob`          decimal(10,2)  DEFAULT NULL,
  `discount`    decimal(8,2)   DEFAULT NULL,
  `astamt`      decimal(8,2)   DEFAULT NULL,
  `ic`          varchar(5)     DEFAULT NULL,
  `alocamt`     decimal(10,2)  DEFAULT NULL,
  `discamt`     decimal(8,2)   DEFAULT NULL,
  `fr`          char(1)        DEFAULT NULL,
  `exchslno`    decimal(10,0)  DEFAULT NULL,
  `taxexternal` char(1)        DEFAULT NULL,
  `dmd`         char(1)        DEFAULT NULL,
  `bal`         decimal(12,2)  DEFAULT NULL,
  `taxperc`     decimal(5,2)   DEFAULT NULL,
  `cst`         char(1)        DEFAULT NULL,
  `tcsperc`     decimal(5,3)   DEFAULT NULL,
  `tcsamt`      decimal(10,2)  DEFAULT NULL,
  `billtype`    varchar(5)     DEFAULT NULL,
  `discperc`    decimal(6,2)   DEFAULT NULL,
  `addr`        varchar(60)    DEFAULT NULL,
  `note`        varchar(40)    DEFAULT NULL,
  `chqbank`     varchar(10)    DEFAULT NULL,
  `chqamt`      decimal(12,2)  DEFAULT NULL,
  `chqno`       varchar(20)    DEFAULT NULL,
  `chqdate`     date           DEFAULT NULL,
  `chqpdc`      char(1)        DEFAULT NULL,
  `pan`         varchar(20)    DEFAULT NULL,
  `statecode`   varchar(10)    DEFAULT NULL,
  `sgst`        decimal(10,2)  DEFAULT NULL,
  `cgst`        decimal(10,2)  DEFAULT NULL,
  `igst`        decimal(10,2)  DEFAULT NULL,
  `mobile`      varchar(20)    DEFAULT NULL,
  `counter`     varchar(10)    DEFAULT NULL,
  `hmc`         decimal(10,2)  DEFAULT NULL,
  `taxonmconly` char(1)        DEFAULT NULL,
  `hmcperc`     decimal(6,2)   DEFAULT NULL,
  `tdsperc`     decimal(6,2)   DEFAULT NULL,
  `tdsamt`      decimal(8,2)   DEFAULT NULL,
  `cbcode`      varchar(10)    DEFAULT NULL,
  `tin`         varchar(15)    DEFAULT NULL,
  `rate24`      decimal(8,2)   DEFAULT NULL,
  `rate18`      decimal(8,2)   DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
