<?php

namespace App\Enums;

use Illuminate\Http\Request;

class Permission
{
    public static function matchPermissionForRequest(Request $request): ?string
    {
        $path = trim($request->path(), '/');
        $normalizedPath = preg_replace('#^api/#i', '', $path) ?: $path;

        if (preg_match('#^customer(?:/.*)?$#i', $path) === 1 || preg_match('#^customer(?:/.*)?$#i', $normalizedPath) === 1) {
            $type = strtoupper(trim((string) $request->query('type', 'C')));
            if ($type === 'F') {
                return 'MDI_STAFF_MASTER';
            }
        }

        return self::matchPermissionForPath($path);
    }

    public static function matchPermissionForPath(string $path): ?string
    {
        $path = trim($path, '/');
        $normalizedPath = preg_replace('#^api/#i', '', $path) ?: $path;

        foreach (self::routePatterns() as $pattern => $permission) {
            $regex = '#^' . str_replace('\*', '.*', preg_quote(trim($pattern, '/'), '#')) . '$#i';
            if (preg_match($regex, $path) === 1 || preg_match($regex, $normalizedPath) === 1) {
                return $permission;
            }
        }

        return null;
    }

    public static function all(): array
    {
        return self::mdiMenus() + [
            'BCSTATUSEDIT' => 'Allow Barcode Status Edit',
            'BCDETAILSEDIT' => 'Allow Barcode Details Edit',
            'BCDETAILSDELETE' => 'Allow Barcode Details Delete',
            'BCCOMPULSORY' => 'BC Compulsory',
            'ALLOWSALESCANCELLATION' => 'Allow Sales Cancellation',
            'ALLOWESTIMATECANCELLATION' => 'Allow Sales Estimate Cancellation',
            'ALLOWPREVNEXTBUTTONSINSALES' => 'Allow Prev / Next Buttons in Sales',
            'ALLOWBCDETEDITINSALES' => 'Allow Edit BC Details in Sales',
            'ITEMADJUSTMENTINSALES' => 'Allow Item Adjustment in Sales',
            'ITEMADJDIFFTYPE' => 'Allow Item Adjustment Different Types',
            'ALLOWPURCHASECONFIRMATION' => 'Allow Purchase Confirmation',
            'ALLOWPMNTCONFIRMATION' => 'Allow Payment Confirmation',
            'KURICOLLNEDIT' => 'Allow Kuri/Scheme Collection Edit',
            'ALLOWORDERBLOCKOPN' => 'Allow Order Block Open',
            'ALLOWBCCREATIONINSMITHJEWLENTRY' => 'Allow Barcode Creation in Jewl Entry',
            'ALLOWJEWLSMITHMANUALDOCNO' => 'Allow Jewl/Smith Manual Doc No',
            'MASTEREDIT' => "Don't Allow Master Edit",
            'MASTERDELETE' => "Don't Allow Master Delete",
            'MASTEROBEDIT' => "Don't Allow Master Opening Balance Edit",
            'JOURNALALTER' => "Don't Allow Journal Alter",
            'ONLINEEDIT' => "Don't Allow Online Edit",
            'PREVIOUSDATE' => "Don't Allow Previous Date Entry",
            'AFTERDATE' => "Don't Allow After Date Entry",
            'SHOWPARTYBAL' => 'Show Party Balance in Transactions',
            'SHOWDISCINRCPT' => 'Show Discount in Receipt',
            'SHOWDISCINPMNT' => 'Show Discount in Payment',
            'SHOWEDITUPDATEINBILLCONFIRMATION' => 'Show Edit/Update in Confirmation',
            'SHOWAVGPCOSTANDVAINSALES' => 'Show Avg Cost / VA% in Sales',
            'SHOWCOSTDETAILSINBCLIST' => 'Show Cost Details in BC List',
            'ADMINBUTTON' => 'Show Admin Button',
            'RATESETUP' => 'Allow Rate Setup',
            'ALLOWSECONDARYDBSYNC' => 'Allow Secondary Save',
            'NOSUPPBALINSEMI' => "Don't Show Supplier Balance in Semi",
            'NOPARTYBALINSEMI' => "Don't Show Party Balance in Semi",
            'NOSMITHBALINSEMI' => "Don't Show Smith Balance in Semi",
            'NOSTAFFBAL' => "Don't Show Staff Balance",
            'CREDIT' => "Don't Allow Credit",
            'NOITEMWGT' => "Don't Show Item Weight",
            'NOTOTSTOCK' => "Don't Show Total Stock",
            'READONLY' => 'Read Only',
        ];
    }

    public static function grouped(): array
    {
        return [
            'MDI System & Admin' => [
                'MDI_DASHBOARD',
                'MDI_APPLICATION_SETTINGS',
                'MDI_ADMINISTRATION',
                'MDI_CUSTOMER_CAMPAIGN',
                'MDI_USER_ACCESS',
                'MDI_ADMIN_USERS',
                'MDI_STATES_ADDING',
                'MDI_AI_INSIGHTS',
                'MDI_PHONE_BOOK',
                'MDI_BACKUP',
                'MDI_YEAR_END_ACCOUNT_CLOSE',
            ],
            'MDI Accounts' => [
                'MDI_ACCOUNTS_AC_LEDGER',
                'MDI_ACCOUNTS_CUSTOMER_BILLWISE_RCPT',
                'MDI_ACCOUNTS_SUPPLIER_BILLWISE_PAYMENT',
                'MDI_ACCOUNTS_DEBIT_CREDIT_NOTE',
                'MDI_ACCOUNTS_RATE_DIFF_ADJUSTMENT',
                'MDI_ACCOUNTS_GROUP_AMT_ALLOCATION',
                'MDI_ACCOUNTS_CHANGE_DUEDATE',
                'MDI_ACCOUNTS_RESTART_DATE',
                'MDI_ACCOUNTS_AMT_WGT_TRANSFER',
                'MDI_ACCOUNTS_PAYMENT_CONFIRMATION',
                'MDI_ACCOUNTS_DENOMINATION_ENTRY',
                'MDI_ACCOUNTS_EXPENSE_VOUCHER_ENTRY',
                'MDI_ACCOUNTS_MASTER',
                'MDI_ACCOUNTS_RECEIPT',
                'MDI_ACCOUNTS_PAYMENT',
                'MDI_ACCOUNTS_SUSPENSE_ENTRY',
                'MDI_ACCOUNTS_SUSPENSE_MASTER',
                'MDI_ACCOUNTS_EDIT_ENTRY',
                'MDI_ACCOUNTS_JOURNAL',
                'MDI_ACCOUNTS_PDC_COLLECTION',
                'MDI_ACCOUNTS_DAILY_STATEMENT',
            ],
            'MDI Sales' => [
                'MDI_SALES_BILL',
                'MDI_SALES_BILL_PRINT',
                'MDI_SALES_BILL_CONFIRMATION',
                'MDI_SALES_BOOK_REPORT',
                'MDI_MONTHLY_SALES_REPORT',
                'MDI_SALES_REGISTER',
                'MDI_SALES_CHECK_LIST',
                'MDI_SALES_RETURN',
                'MDI_SALES_RETURN_REGISTER',
                'MDI_NET_SALES_REPORT',
                'MDI_DELIVERY_STATUS_REPORT',
                'MDI_POINT_CARD_POINTS_REPORT',
            ],
            'MDI Purchase' => [
                'MDI_PURCHASE_BILL',
                'MDI_PURCHASE_BILL_CONFIRMATION',
                'MDI_PURCHASE_RETURN',
                'MDI_PURCHASE_CHECK_LIST',
                'MDI_PURCHASE_BOOK',
                'MDI_PURCHASE_REGISTER',
                'MDI_PURCHASE_RETURN_REGISTER',
                'MDI_DIAMOND_PURCHASE_BILL',
                'MDI_DIAMOND_PURCHASE_RETURN',
            ],
            'MDI Stock & Barcode' => [
                'MDI_STOCK_OPENING_STOCK',
                'MDI_STOCK_LEDGER',
                'MDI_STOCK_PERIOD_LEDGER',
                'MDI_STOCK_ITEM_HISTORY',
                'MDI_STOCK_REGISTER',
                'MDI_STOCK_VERIFICATION',
                'MDI_STOCK_SUMMARY_COST_WISE',
                'MDI_STOCK_SUMMARY_RATE_WISE',
                'MDI_STOCK_SUSPENSE_ENTRY',
                'MDI_ITEM_STOCK_ADJUSTMENT',
                'MDI_ITEM_STOCK_ADJUSTMENT_MULTI',
                'MDI_ITEM_STOCK_ADD_LESS',
                'MDI_ITEM_STOCK_ADJUSTMENT_COMPARE',
                'MDI_BARCODE_SINGLE_ENTRY',
                'MDI_BARCODE_MULTI_ENTRY',
                'MDI_BARCODE_REGISTER',
                'MDI_BARCODE_PROFIT',
                'MDI_COUNTER_ISSUE',
            ],
            'MDI Orders & Goldsmith' => [
                'MDI_ORDER_BILL',
                'MDI_ORDER_UPDATE',
                'MDI_ORDER_BLOCK',
                'MDI_ORDER_SALE',
                'MDI_ORDER_RATE_FIX',
                'MDI_ORDER_REPRINT',
                'MDI_ORDER_CANCEL',
                'MDI_GOLDSMITH_TRANSACTIONS',
                'MDI_GOLD_RATE_STORY',
                'MDI_WGT_RCPT_PMNT',
                'MDI_PARTY_OP_WEIGHT',
                'MDI_DEPOSITORS_INT_POST',
                'MDI_PURITY_TESTING',
                'MDI_PURITY_CERTIFICATE',
                'MDI_REFINERY_BILL',
                'MDI_RUFF_WORK',
                'MDI_OTHER_ITEM_TRANS',
                'MDI_SCHEME_COLLECTION',
                'MDI_SCHEME_CLOSE',
                'MDI_SCHEME_INTEREST',
                'MDI_SCHEME_PASSBOOK',
                'MDI_SCHEME_REFUND',
            ],
            'MDI Customers & Masters' => [
                'MDI_CUSTOMER',
                'MDI_STAFF_MASTER',
                'MDI_CUSTOMER_POPUP',
                'MDI_SEARCH_ITEMS',
                'MDI_GROUPS',
                'MDI_SUB_GROUPS',
                'MDI_PURITY_TYPE',
                'MDI_REGIONAL_HELP',
                'MDI_ITEM_TEMP',
                'MDI_ITEM_HELP',
                'MDI_OTHER_ITEMS',
                'MDI_COUNTERS',
                'MDI_WASTAGE_TABLE',
                'MDI_BILL_PREFIX',
                'MDI_PARTY_MC_TABLE',
                'MDI_MC_TABLE',
                'MDI_GIFT_TABLE',
                'MDI_POINT_CARD',
                'MDI_DENOMINATION_MASTER',
                'MDI_OP_BILL_CREATION_CUSTOMERS',
                'MDI_ITEM_MASTER',
                'MDI_STOCK_TYPE',
                'MDI_MODEL_MASTER',
                'MDI_REORDER',
                'MDI_RATE_UPDATE',
                'MDI_RATE_HISTORY',
                'MDI_KURI_DETAILS',
                'MDI_KURI_TYPE_MASTER',
            ],
            'MDI Reports & Books' => [
                'MDI_DAYBOOK',
                'MDI_DAY_SUMMARY',
                'MDI_MARKED_LIST',
                'MDI_MC_PROFIT',
                'MDI_VA_CHECK_LIST',
                'MDI_VA_CHECK_REPORT',
                'MDI_FINANCIAL_STATEMENTS',
                'MDI_SMITH_BOOK',
                'MDI_TAX_PURCHASE_BOOK',
                'MDI_JEWLLERY_BOOK',
                'MDI_OUTSTANDING_TAX',
                'MDI_FINANCIAL_REPORTS',
                'MDI_BARCODE_REPORTS',
                'MDI_CUSTOMER_ANALYTICS',
                'MDI_DEPOSIT_ANALYTICS',
                'MDI_GOLDSMITH_ANALYTICS',
                'MDI_GST_TAX_REPORTS',
                'MDI_INVENTORY_REPORTS',
                'MDI_JEWELLERY_ANALYTICS',
                'MDI_ORDER_ANALYTICS',
                'MDI_OTHER_ITEM_REPORTS',
                'MDI_OTHER_REPORTS',
                'MDI_CHITTY_ANALYTICS',
                'MDI_STAFF_ANALYTICS',
                'MDI_SUPPLIER_ANALYTICS',
                'MDI_REFINERY_ANALYTICS',
                'MDI_REPAIR_ANALYTICS',
            ],
            'MDI Staff & Repair' => [
                'MDI_STAFF_TRANSACTION',
                'MDI_STAFF_LOG_UPDATE',
                'MDI_STAFF_LEAVE_ENTRY',
                'MDI_STAFF_WGT_TRANSACTION',
                'MDI_REPAIR_COMPLAINTS',
                'MDI_REPAIR_RECEIPT_MEMO_PARTY',
                'MDI_REPAIR_RETURN',
            ],
            'Barcode Management' => [
                'BCSTATUSEDIT',
                'BCDETAILSEDIT',
                'BCDETAILSDELETE',
                'BCCOMPULSORY',
                'ALLOWBCDETEDITINSALES',
                'ALLOWBCCREATIONINSMITHJEWLENTRY',
            ],
            'Sales & Orders' => [
                'ALLOWSALESCANCELLATION',
                'ALLOWESTIMATECANCELLATION',
                'ALLOWPREVNEXTBUTTONSINSALES',
                'ITEMADJUSTMENTINSALES',
                'ITEMADJDIFFTYPE',
                'ALLOWORDERBLOCKOPN',
            ],
            'Purchase & Payment' => [
                'ALLOWPURCHASECONFIRMATION',
                'ALLOWPMNTCONFIRMATION',
                'KURICOLLNEDIT',
            ],
            'Jewellery / Smith' => [
                'ALLOWJEWLSMITHMANUALDOCNO',
            ],
            'Master Data' => [
                'MASTEREDIT',
                'MASTERDELETE',
                'MASTEROBEDIT',
                'JOURNALALTER',
                'ONLINEEDIT',
                'RATESETUP',
            ],
            'Transactions' => [
                'PREVIOUSDATE',
                'AFTERDATE',
                'CREDIT',
            ],
            'Display Options' => [
                'SHOWPARTYBAL',
                'SHOWDISCINRCPT',
                'SHOWDISCINPMNT',
                'SHOWEDITUPDATEINBILLCONFIRMATION',
                'SHOWAVGPCOSTANDVAINSALES',
                'SHOWCOSTDETAILSINBCLIST',
                'NOSUPPBALINSEMI',
                'NOPARTYBALINSEMI',
                'NOSMITHBALINSEMI',
                'NOSTAFFBAL',
                'NOITEMWGT',
                'NOTOTSTOCK',
            ],
            'Access Control' => [
                'ADMINBUTTON',
                'ALLOWSECONDARYDBSYNC',
                'READONLY',
            ],
        ];
    }

    public static function groupedLabels(): array
    {
        $all = self::all();
        $grouped = [];

        foreach (self::grouped() as $group => $keys) {
            $grouped[$group] = [];
            foreach ($keys as $key) {
                $grouped[$group][$key] = $all[$key] ?? $key;
            }
        }

        return $grouped;
    }

    private static function mdiMenus(): array
    {
        return [
            'MDI_DASHBOARD' => 'Dashboard (/dashboard)',
            'MDI_APPLICATION_SETTINGS' => 'Application Settings (/application-settings)',
            'MDI_ADMINISTRATION' => 'Administration (/administration)',
            'MDI_CUSTOMER_CAMPAIGN' => 'Customer Campaign (/customer-campaign)',
            'MDI_USER_ACCESS' => 'User Access (/user-access)',
            'MDI_ADMIN_USERS' => 'Admin Users (/admin/users)',
            'MDI_STATES_ADDING' => 'States Adding (/states-adding)',
            'MDI_AI_INSIGHTS' => 'AI Analytics (/ai-insights)',
            'MDI_PHONE_BOOK' => 'Contact Directory (/phone-book)',
            'MDI_BACKUP' => 'Data Backup & Restore (/backup)',
            'MDI_YEAR_END_ACCOUNT_CLOSE' => 'Financial Year Closing (/year-end-account-close)',
            'MDI_ACCOUNTS_AC_LEDGER' => 'A/c Ledger (/accounts/ac-ledger)',
            'MDI_ACCOUNTS_CUSTOMER_BILLWISE_RCPT' => 'Customer Billwise Receipt (/accounts/customer-billwise-rcpt)',
            'MDI_ACCOUNTS_SUPPLIER_BILLWISE_PAYMENT' => 'Supplier Billwise Payment (/accounts/supplier-billwise-payment)',
            'MDI_ACCOUNTS_DEBIT_CREDIT_NOTE' => 'Debit / Credit Note (/accounts/debit-credit-note)',
            'MDI_ACCOUNTS_RATE_DIFF_ADJUSTMENT' => 'Rate Diff Adjustment (/accounts/rate-diff-adjustment)',
            'MDI_ACCOUNTS_GROUP_AMT_ALLOCATION' => 'Group Amount Allocation (/accounts/group-amt-allocation)',
            'MDI_ACCOUNTS_CHANGE_DUEDATE' => 'Change Due Date (/accounts/change-duedate)',
            'MDI_ACCOUNTS_RESTART_DATE' => 'Account Restart Date (/accounts/restart-date)',
            'MDI_ACCOUNTS_AMT_WGT_TRANSFER' => 'Amt/Wgt Transfer Entry (/accounts/amt-wgt-transfer-entry)',
            'MDI_ACCOUNTS_PAYMENT_CONFIRMATION' => 'Payment Confirmation (/accounts/payment-confirmation)',
            'MDI_ACCOUNTS_DENOMINATION_ENTRY' => 'Denomination Entry (/accounts/denomination-entry)',
            'MDI_ACCOUNTS_EXPENSE_VOUCHER_ENTRY' => 'Expense Voucher Entry (/accounts/expense-voucher-entry)',
            'MDI_ACCOUNTS_MASTER' => 'Account Master (/accounts/master/account)',
            'MDI_ACCOUNTS_RECEIPT' => 'Receipt (/accounts/receipt)',
            'MDI_ACCOUNTS_PAYMENT' => 'Payment (/accounts/payment)',
            'MDI_ACCOUNTS_SUSPENSE_ENTRY' => 'Suspense Entry (/accounts/suspense-entry)',
            'MDI_ACCOUNTS_SUSPENSE_MASTER' => 'Suspense Master (/accounts/suspense-master)',
            'MDI_ACCOUNTS_EDIT_ENTRY' => 'Account Edit Entry (/accounts/edit-entry)',
            'MDI_ACCOUNTS_JOURNAL' => 'Journal (/accounts/journal)',
            'MDI_ACCOUNTS_PDC_COLLECTION' => 'PDC Collection (/accounts/pdc-collection)',
            'MDI_ACCOUNTS_DAILY_STATEMENT' => 'Daily Statement (/accounts/daily-statement)',
            'MDI_SALES_BILL' => 'Sales Bill (/sales-bill)',
            'MDI_SALES_BILL_PRINT' => 'Sales Bill Print (/sales-bill-print)',
            'MDI_SALES_BILL_CONFIRMATION' => 'Sales Bill Confirmation (/sales-bill-confirmation)',
            'MDI_SALES_BOOK_REPORT' => 'Sales Book Report (/sales-book-report)',
            'MDI_MONTHLY_SALES_REPORT' => 'Monthly Sales Report (/monthly-sales-report)',
            'MDI_SALES_REGISTER' => 'Sales Register (/sales-register)',
            'MDI_SALES_CHECK_LIST' => 'Sales Check List (/sales-check-list)',
            'MDI_SALES_RETURN' => 'Sales Return (/sales-return)',
            'MDI_SALES_RETURN_REGISTER' => 'Sales Return Register (/sales-return-register)',
            'MDI_NET_SALES_REPORT' => 'Net Sales Report (/net-sales)',
            'MDI_DELIVERY_STATUS_REPORT' => 'Delivery Status Report (/delivery-status)',
            'MDI_POINT_CARD_POINTS_REPORT' => 'Point Card Points Report (/point-card-points)',
            'MDI_PURCHASE_BILL' => 'Purchase Bill (/purchase-bill)',
            'MDI_PURCHASE_BILL_CONFIRMATION' => 'Purchase Bill Confirmation (/purchase-bill-confirmation)',
            'MDI_PURCHASE_RETURN' => 'Purchase Return (/purchase-return)',
            'MDI_PURCHASE_CHECK_LIST' => 'Purchase Check List (/purchase-check-list)',
            'MDI_PURCHASE_BOOK' => 'Purchase Book (/purchase-book)',
            'MDI_PURCHASE_REGISTER' => 'Purchase Register (/purchase-register)',
            'MDI_PURCHASE_RETURN_REGISTER' => 'Purchase Return Register (/purchase-return-register)',
            'MDI_DIAMOND_PURCHASE_BILL' => 'Diamond Purchase Bill (/diamond-purchase-bill)',
            'MDI_DIAMOND_PURCHASE_RETURN' => 'Diamond Purchase Return (/diamond-purchase-return)',
            'MDI_STOCK_OPENING_STOCK' => 'Stock Opening Stock (/stock/opening-stock)',
            'MDI_STOCK_LEDGER' => 'Stock Ledger (/stock/ledger)',
            'MDI_STOCK_PERIOD_LEDGER' => 'Stock Period Ledger (/stock/period-ledger)',
            'MDI_STOCK_ITEM_HISTORY' => 'Stock Item History (/stock/item-history)',
            'MDI_STOCK_REGISTER' => 'Stock Register (/stock-register)',
            'MDI_STOCK_VERIFICATION' => 'Stock Verification (/stock-verification)',
            'MDI_STOCK_SUMMARY_COST_WISE' => 'Stock Summary Cost Wise (/stock-summary-cost-wise)',
            'MDI_STOCK_SUMMARY_RATE_WISE' => 'Stock Summary Rate Wise (/stock-summary-rate-wise)',
            'MDI_STOCK_SUSPENSE_ENTRY' => 'Stock Suspense Entry (/stock-suspense-entry)',
            'MDI_ITEM_STOCK_ADJUSTMENT' => 'Item Stock Adjustment (/item-stock-adjustment)',
            'MDI_ITEM_STOCK_ADJUSTMENT_MULTI' => 'Item Stock Adjustment Multi (/item-stock-adjustment-multi)',
            'MDI_ITEM_STOCK_ADD_LESS' => 'Item Stock Add/Less (/item-stock-add-less)',
            'MDI_ITEM_STOCK_ADJUSTMENT_COMPARE' => 'Item Stock Adjustment Compare (/item-stock-adjustment-compare)',
            'MDI_BARCODE_SINGLE_ENTRY' => 'Barcode Single Entry (/barcode-single-entry)',
            'MDI_BARCODE_MULTI_ENTRY' => 'Barcode Multi Entry (/barcode-multi-entry)',
            'MDI_BARCODE_REGISTER' => 'Barcode Register (/barcode-register)',
            'MDI_BARCODE_PROFIT' => 'Barcode Profit Report (/barcode-profit)',
            'MDI_COUNTER_ISSUE' => 'Counter Issue (/counter-issue)',
            'MDI_ORDER_BILL' => 'Order Bill (/order-bill)',
            'MDI_ORDER_UPDATE' => 'Order Update (/order-update)',
            'MDI_ORDER_BLOCK' => 'Order Block (/order-block)',
            'MDI_ORDER_SALE' => 'Order Sale (/order-sale)',
            'MDI_ORDER_RATE_FIX' => 'Order Rate Fix (/order-rate-fix)',
            'MDI_ORDER_REPRINT' => 'Order Reprint (/order-reprint)',
            'MDI_ORDER_CANCEL' => 'Order Cancel (/order-cancel)',
            'MDI_GOLDSMITH_TRANSACTIONS' => 'Goldsmith Transactions (/goldsmith-transactions)',
            'MDI_GOLD_RATE_STORY' => 'Gold Rate Story (/gold-rate-story)',
            'MDI_WGT_RCPT_PMNT' => 'Weight Receipt / Payment (/wgt-rcpt-pmnt)',
            'MDI_PARTY_OP_WEIGHT' => 'Party Opening Weight (/party-op-weight)',
            'MDI_DEPOSITORS_INT_POST' => 'Depositors Interest Posting (/depositors-int-post)',
            'MDI_PURITY_TESTING' => 'Purity Testing (/purity-testing)',
            'MDI_PURITY_CERTIFICATE' => 'Purity Certificate (/purity-certificate)',
            'MDI_RUFF_WORK' => 'Ruff Work (/ruff-work)',
            'MDI_OTHER_ITEM_TRANS' => 'Other Item Transaction (/other-item-trans)',
            'MDI_CUSTOMER' => 'Customer (/customer)',
            'MDI_STAFF_MASTER' => 'Staff Master (/customer?type=F)',
            'MDI_CUSTOMER_POPUP' => 'Customer Popup Routes (/customer/popup/routes)',
            'MDI_SEARCH_ITEMS' => 'Search Items (/search-items)',
            'MDI_GROUPS' => 'Groups (/groups)',
            'MDI_SUB_GROUPS' => 'Sub Groups (/sub-groups)',
            'MDI_PURITY_TYPE' => 'Purity Type (/purity-type)',
            'MDI_REGIONAL_HELP' => 'Regional Help (/regional-help)',
            'MDI_ITEM_TEMP' => 'Item Temp (/item-temp)',
            'MDI_ITEM_HELP' => 'Item Help (/item-help)',
            'MDI_OTHER_ITEMS' => 'Other Items (/other-items)',
            'MDI_COUNTERS' => 'Counters (/counters)',
            'MDI_WASTAGE_TABLE' => 'Wastage Table (/wastage-table)',
            'MDI_BILL_PREFIX' => 'Bill Prefix (/bill-prefix)',
            'MDI_PARTY_MC_TABLE' => 'Party MC Table (/partymctable)',
            'MDI_MC_TABLE' => 'MC Table (/mctable)',
            'MDI_GIFT_TABLE' => 'Gift Table (/gift-table)',
            'MDI_POINT_CARD' => 'Point Card (/point-card)',
            'MDI_DENOMINATION_MASTER' => 'Denomination Master (/denomination-master)',
            'MDI_OP_BILL_CREATION_CUSTOMERS' => 'Opening Bill Creation Customers (/op-bill-creation/customers)',
            'MDI_ITEM_MASTER' => 'Item Master (/item-master)',
            'MDI_STOCK_TYPE' => 'Stock Type (/stocktype)',
            'MDI_MODEL_MASTER' => 'Model Master (/models)',
            'MDI_REORDER' => 'Reorder (/reorder)',
            'MDI_RATE_UPDATE' => 'Rate Update (/rate/update)',
            'MDI_RATE_HISTORY' => 'Rate History (/rate/history)',
            'MDI_KURI_DETAILS' => 'Kuri Details (/kuri-details)',
            'MDI_KURI_TYPE_MASTER' => 'Kuri Type Master (/kuri-type-master)',
            'MDI_SCHEME_COLLECTION' => 'Scheme / Kuri Collection (/kuri-collection)',
            'MDI_SCHEME_CLOSE' => 'Close Scheme / Kuri (/kuri-finish/close-scheme)',
            'MDI_SCHEME_INTEREST' => 'Scheme / Kuri Interest Posting (/kuri-int-post)',
            'MDI_SCHEME_PASSBOOK' => 'Passbook Print (/passbook-print)',
            'MDI_SCHEME_REFUND' => 'Scheme / Kuri Refund (/kuri-finish/refund)',
            'MDI_DAYBOOK' => 'Day Book (/daybook)',
            'MDI_DAY_SUMMARY' => 'Day Summary (/day-summary)',
            'MDI_MARKED_LIST' => 'Marked List (/marked-list)',
            'MDI_MC_PROFIT' => 'MC Profit (/mc-profit)',
            'MDI_VA_CHECK_LIST' => 'VA Check List (/va-check-list)',
            'MDI_VA_CHECK_REPORT' => 'VA Check Report (/va-check-report)',
            'MDI_FINANCIAL_STATEMENTS' => 'Financial Statements (/reports/financial-statements)',
            'MDI_SMITH_BOOK' => 'Smith Book (/smith-book)',
            'MDI_TAX_PURCHASE_BOOK' => 'Tax Purchase Book (/tax-purchase-book)',
            'MDI_JEWLLERY_BOOK' => 'Jewllery Book (/jewllery-book)',
            'MDI_OUTSTANDING_TAX' => 'Outstanding Tax (/outstanding-tax)',
            'MDI_FINANCIAL_REPORTS' => 'Financial Reports (Advanced Reports Menu)',
            'MDI_BARCODE_REPORTS' => 'Barcode Reports (Advanced Reports Menu)',
            'MDI_CUSTOMER_ANALYTICS' => 'Customer Analytics (Advanced Reports Menu)',
            'MDI_DEPOSIT_ANALYTICS' => 'Deposit Analytics (Advanced Reports Menu)',
            'MDI_GOLDSMITH_ANALYTICS' => 'Goldsmith Analytics (Advanced Reports Menu)',
            'MDI_GST_TAX_REPORTS' => 'GST & Tax Reports (Advanced Reports Menu)',
            'MDI_INVENTORY_REPORTS' => 'Inventory Reports (Advanced Reports Menu)',
            'MDI_JEWELLERY_ANALYTICS' => 'Jewellery Analytics (Advanced Reports Menu)',
            'MDI_ORDER_ANALYTICS' => 'Order Analytics (Advanced Reports Menu)',
            'MDI_OTHER_ITEM_REPORTS' => 'Other Item Reports (Advanced Reports Menu)',
            'MDI_OTHER_REPORTS' => 'Other Reports (Advanced Reports Menu)',
            'MDI_CHITTY_ANALYTICS' => 'Chitty Management Analytics (Advanced Reports Menu)',
            'MDI_STAFF_ANALYTICS' => 'Staff Analytics (Advanced Reports Menu)',
            'MDI_SUPPLIER_ANALYTICS' => 'Supplier Analytics (Advanced Reports Menu)',
            'MDI_REFINERY_ANALYTICS' => 'Refinery Analytics (Advanced Reports Menu)',
            'MDI_REPAIR_ANALYTICS' => 'Repair Analytics (Advanced Reports Menu)',
            'MDI_STAFF_TRANSACTION' => 'Staff Transaction (/staff-transaction)',
            'MDI_STAFF_LOG_UPDATE' => 'Staff Log Update (/staff-log-update)',
            'MDI_STAFF_LEAVE_ENTRY' => 'Staff Leave Entry (/staff-leave-entry)',
            'MDI_STAFF_WGT_TRANSACTION' => 'Staff Weight Transaction (/staff-wgt-transaction)',
            'MDI_REPAIR_COMPLAINTS' => 'Repair Complaints (/repair-complaints)',
            'MDI_REPAIR_RECEIPT_MEMO_PARTY' => 'Repair Receipt Memo To Party (/remake-rcpt-memo-to-party)',
            'MDI_REPAIR_RETURN' => 'Repair Return (/repair-return)',
            'MDI_REFINERY_BILL' => 'Refinery Bill & Return (/refinery-bill, /refinery-return)',
        ];
    }

    public static function routePatternsForUi(): array
    {
        return self::routePatterns();
    }

    private static function routePatterns(): array
    {
        return [
            'dashboard' => 'MDI_DASHBOARD',
            'application-settings*' => 'MDI_APPLICATION_SETTINGS',
            'administration*' => 'MDI_ADMINISTRATION',
            'customer-campaign*' => 'MDI_CUSTOMER_CAMPAIGN',
            'user-access*' => 'MDI_USER_ACCESS',
            'admin/users*' => 'MDI_ADMIN_USERS',
            'states-adding*' => 'MDI_STATES_ADDING',
            'ai-insights*' => 'MDI_AI_INSIGHTS',
            'phone-book*' => 'MDI_PHONE_BOOK',
            'backup*' => 'MDI_BACKUP',
            'year-end-account-close*' => 'MDI_YEAR_END_ACCOUNT_CLOSE',
            'accounts/ac-ledger*' => 'MDI_ACCOUNTS_AC_LEDGER',
            'accounts/customer-billwise-rcpt*' => 'MDI_ACCOUNTS_CUSTOMER_BILLWISE_RCPT',
            'accounts/supplier-billwise-payment*' => 'MDI_ACCOUNTS_SUPPLIER_BILLWISE_PAYMENT',
            'accounts/debit-credit-note*' => 'MDI_ACCOUNTS_DEBIT_CREDIT_NOTE',
            'accounts/rate-diff-adjustment*' => 'MDI_ACCOUNTS_RATE_DIFF_ADJUSTMENT',
            'accounts/group-amt-allocation*' => 'MDI_ACCOUNTS_GROUP_AMT_ALLOCATION',
            'accounts/change-duedate*' => 'MDI_ACCOUNTS_CHANGE_DUEDATE',
            'accounts/restart-date*' => 'MDI_ACCOUNTS_RESTART_DATE',
            'accounts/amt-wgt-transfer-entry*' => 'MDI_ACCOUNTS_AMT_WGT_TRANSFER',
            'accounts/payment-confirmation*' => 'MDI_ACCOUNTS_PAYMENT_CONFIRMATION',
            'accounts/denomination-entry*' => 'MDI_ACCOUNTS_DENOMINATION_ENTRY',
            'accounts/expense-voucher-entry*' => 'MDI_ACCOUNTS_EXPENSE_VOUCHER_ENTRY',
            'accounts/master/*' => 'MDI_ACCOUNTS_MASTER',
            'accounts/receipt*' => 'MDI_ACCOUNTS_RECEIPT',
            'accounts/payment*' => 'MDI_ACCOUNTS_PAYMENT',
            'accounts/suspense-entry*' => 'MDI_ACCOUNTS_SUSPENSE_ENTRY',
            'accounts/suspense-master*' => 'MDI_ACCOUNTS_SUSPENSE_MASTER',
            'accounts/edit-entry*' => 'MDI_ACCOUNTS_EDIT_ENTRY',
            'accounts/journal*' => 'MDI_ACCOUNTS_JOURNAL',
            'accounts/pdc-collection*' => 'MDI_ACCOUNTS_PDC_COLLECTION',
            'accounts/daily-statement*' => 'MDI_ACCOUNTS_DAILY_STATEMENT',
            'accounts/cash-book*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/bank-book*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/yearly-cash-balance*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/pdc-report*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/journal-report*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/all-trans-report*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/chart-of-accounts*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/non-transactional-days-report*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/ac-receivable-payable-summary*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/group-ac-summary*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/groupwise-expanded-list*' => 'MDI_FINANCIAL_REPORTS',
            'accounts/rcpt-pmnt-report*' => 'MDI_FINANCIAL_REPORTS',
            'reports/avg-rate-profit*' => 'MDI_FINANCIAL_REPORTS',
            'cash-balance*' => 'MDI_FINANCIAL_REPORTS',
            'cash-flow-report*' => 'MDI_FINANCIAL_REPORTS',
            'integrity-checking*' => 'MDI_FINANCIAL_REPORTS',
            'sales-bill-confirmation*' => 'MDI_SALES_BILL_CONFIRMATION',
            'sales-bill-print*' => 'MDI_SALES_BILL_PRINT',
            'sales-bill*' => 'MDI_SALES_BILL',
            'sales-book-report*' => 'MDI_SALES_BOOK_REPORT',
            'monthly-sales-report*' => 'MDI_MONTHLY_SALES_REPORT',
            'sales-register*' => 'MDI_SALES_REGISTER',
            'sales-check-list*' => 'MDI_SALES_CHECK_LIST',
            'sales-return-register*' => 'MDI_SALES_RETURN_REGISTER',
            'sales-return*' => 'MDI_SALES_RETURN',
            'net-sales*' => 'MDI_NET_SALES_REPORT',
            'delivery-status*' => 'MDI_DELIVERY_STATUS_REPORT',
            'point-card-points*' => 'MDI_POINT_CARD_POINTS_REPORT',
            'purchase-bill-confirmation*' => 'MDI_PURCHASE_BILL_CONFIRMATION',
            'purchase-bill*' => 'MDI_PURCHASE_BILL',
            'purchase-return-register*' => 'MDI_PURCHASE_RETURN_REGISTER',
            'purchase-return*' => 'MDI_PURCHASE_RETURN',
            'purchase-check-list*' => 'MDI_PURCHASE_CHECK_LIST',
            'purchase-book*' => 'MDI_PURCHASE_BOOK',
            'purchase-register*' => 'MDI_PURCHASE_REGISTER',
            'diamond-purchase-bill*' => 'MDI_DIAMOND_PURCHASE_BILL',
            'diamond-purchase-return*' => 'MDI_DIAMOND_PURCHASE_RETURN',
            'stock/opening-stock*' => 'MDI_STOCK_OPENING_STOCK',
            'stock/ledger*' => 'MDI_STOCK_LEDGER',
            'stock/period-ledger*' => 'MDI_STOCK_PERIOD_LEDGER',
            'stock/item-history*' => 'MDI_STOCK_ITEM_HISTORY',
            'stock-register*' => 'MDI_STOCK_REGISTER',
            'stock-verification*' => 'MDI_STOCK_VERIFICATION',
            'stock-summary-cost-wise*' => 'MDI_STOCK_SUMMARY_COST_WISE',
            'stock-summary-rate-wise*' => 'MDI_STOCK_SUMMARY_RATE_WISE',
            'stock-suspense-entry*' => 'MDI_STOCK_SUSPENSE_ENTRY',
            'item-stock-adjustment*' => 'MDI_ITEM_STOCK_ADJUSTMENT',
            'item-stock-adjustment-multi*' => 'MDI_ITEM_STOCK_ADJUSTMENT_MULTI',
            'item-stock-add-less*' => 'MDI_ITEM_STOCK_ADD_LESS',
            'item-stock-adjustment-compare*' => 'MDI_ITEM_STOCK_ADJUSTMENT_COMPARE',
            'barcode-single-entry*' => 'MDI_BARCODE_SINGLE_ENTRY',
            'barcode-multi-entry*' => 'MDI_BARCODE_MULTI_ENTRY',
            'barcode-register*' => 'MDI_BARCODE_REGISTER',
            'barcode-profit*' => 'MDI_BARCODE_PROFIT',
            'barcode-list*' => 'MDI_BARCODE_REPORTS',
            'barcode-stock-verify*' => 'MDI_BARCODE_REPORTS',
            'barcode-samt-list*' => 'MDI_BARCODE_REPORTS',
            'barcode-history*' => 'MDI_BARCODE_REPORTS',
            'barcode-stock-list*' => 'MDI_BARCODE_REPORTS',
            'barcode-entry-comparison*' => 'MDI_BARCODE_REPORTS',
            'diamond-stone-stock*' => 'MDI_BARCODE_REPORTS',
            'counter-issue*' => 'MDI_COUNTER_ISSUE',
            'order-bill*' => 'MDI_ORDER_BILL',
            'order-update*' => 'MDI_ORDER_UPDATE',
            'order-block*' => 'MDI_ORDER_BLOCK',
            'order-sale*' => 'MDI_ORDER_SALE',
            'order-rate-fix*' => 'MDI_ORDER_RATE_FIX',
            'order-reprint*' => 'MDI_ORDER_REPRINT',
            'order-cancel*' => 'MDI_ORDER_CANCEL',
            'goldsmith-transactions*' => 'MDI_GOLDSMITH_TRANSACTIONS',
            'goldsmith-transactions-report*' => 'MDI_GOLDSMITH_TRANSACTIONS',
            'gold-rate-story*' => 'MDI_GOLD_RATE_STORY',
            'wgt-rcpt-pmnt*' => 'MDI_WGT_RCPT_PMNT',
            'party-op-weight*' => 'MDI_PARTY_OP_WEIGHT',
            'depositors-int-post*' => 'MDI_DEPOSITORS_INT_POST',
            'purity-testing*' => 'MDI_PURITY_TESTING',
            'purity-certificate*' => 'MDI_PURITY_CERTIFICATE',
            'refinery-bill*' => 'MDI_REFINERY_BILL',
            'refinery-return*' => 'MDI_REFINERY_BILL',
            'ruff-work*' => 'MDI_RUFF_WORK',
            'other-item-trans*' => 'MDI_OTHER_ITEM_TRANS',
            'customer/popup/*' => 'MDI_CUSTOMER_POPUP',
            'customer*' => 'MDI_CUSTOMER',
            'search-items*' => 'MDI_SEARCH_ITEMS',
            'groups*' => 'MDI_GROUPS',
            'sub-groups*' => 'MDI_SUB_GROUPS',
            'purity-type*' => 'MDI_PURITY_TYPE',
            'regional-help*' => 'MDI_REGIONAL_HELP',
            'item-temp*' => 'MDI_ITEM_TEMP',
            'item-help*' => 'MDI_ITEM_HELP',
            'other-items*' => 'MDI_OTHER_ITEMS',
            'counters*' => 'MDI_COUNTERS',
            'wastage-table*' => 'MDI_WASTAGE_TABLE',
            'bill-prefix*' => 'MDI_BILL_PREFIX',
            'partymctable*' => 'MDI_PARTY_MC_TABLE',
            'mctable*' => 'MDI_MC_TABLE',
            'gift-table*' => 'MDI_GIFT_TABLE',
            'point-card*' => 'MDI_POINT_CARD',
            'denomination-master*' => 'MDI_DENOMINATION_MASTER',
            'op-bill-creation/customers*' => 'MDI_OP_BILL_CREATION_CUSTOMERS',
            'item-master*' => 'MDI_ITEM_MASTER',
            'stocktype*' => 'MDI_STOCK_TYPE',
            'models*' => 'MDI_MODEL_MASTER',
            'reorder*' => 'MDI_REORDER',
            'rate/update*' => 'MDI_RATE_UPDATE',
            'rate/history*' => 'MDI_RATE_HISTORY',
            'kuri-details*' => 'MDI_KURI_DETAILS',
            'kuri-type-master*' => 'MDI_KURI_TYPE_MASTER',
            'kuri-collection*' => 'MDI_SCHEME_COLLECTION',
            'kuri-int-post*' => 'MDI_SCHEME_INTEREST',
            'kuri-finish/close-scheme*' => 'MDI_SCHEME_CLOSE',
            'kuri-finish/refund*' => 'MDI_SCHEME_REFUND',
            'passbook-print*' => 'MDI_SCHEME_PASSBOOK',
            'daybook*' => 'MDI_DAYBOOK',
            'day-summary*' => 'MDI_DAY_SUMMARY',
            'customers/credit-bill-details*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/summary*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/received-details*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/payment-details*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/sales-summary*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/billwise-details*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/bill-collection-details*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/duedate-report*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/party-history*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/visit-report*' => 'MDI_CUSTOMER_ANALYTICS',
            'customers/list*' => 'MDI_CUSTOMER_ANALYTICS',
            'suppliers/duedate-report*' => 'MDI_SUPPLIER_ANALYTICS',
            'suppliers/list*' => 'MDI_SUPPLIER_ANALYTICS',
            'deposit-reports/*' => 'MDI_DEPOSIT_ANALYTICS',
            'cost-list*' => 'MDI_INVENTORY_REPORTS',
            'item-rate-report*' => 'MDI_INVENTORY_REPORTS',
            'rate-history' => 'MDI_INVENTORY_REPORTS',
            'itemwise-profit*' => 'MDI_INVENTORY_REPORTS',
            'item-movement*' => 'MDI_INVENTORY_REPORTS',
            'model-transfer-report*' => 'MDI_INVENTORY_REPORTS',
            'stone-trans-analysis*' => 'MDI_INVENTORY_REPORTS',
            'trans-ra-report*' => 'MDI_INVENTORY_REPORTS',
            'item-stock-party-wgt-report*' => 'MDI_INVENTORY_REPORTS',
            'marked-list*' => 'MDI_MARKED_LIST',
            'mc-profit*' => 'MDI_MC_PROFIT',
            'va-check-list*' => 'MDI_VA_CHECK_LIST',
            'va-check-report*' => 'MDI_VA_CHECK_REPORT',
            'reports/financial-statements*' => 'MDI_FINANCIAL_STATEMENTS',
            'smith-book*' => 'MDI_SMITH_BOOK',
            'tax-purchase-book*' => 'MDI_TAX_PURCHASE_BOOK',
            'jewllery-book*' => 'MDI_JEWLLERY_BOOK',
            'outstanding-tax*' => 'MDI_OUTSTANDING_TAX',
            'order-entry-report*' => 'MDI_ORDER_ANALYTICS',
            'order-pending-register*' => 'MDI_ORDER_ANALYTICS',
            'order-enquiry*' => 'MDI_ORDER_ANALYTICS',
            'order-pending-details*' => 'MDI_ORDER_ANALYTICS',
            'order-returns*' => 'MDI_ORDER_ANALYTICS',
            'order-advance-report*' => 'MDI_ORDER_ANALYTICS',
            'order-profit-analysis*' => 'MDI_ORDER_ANALYTICS',
            'order-sample-stock*' => 'MDI_ORDER_ANALYTICS',
            'order-nos-list*' => 'MDI_ORDER_ANALYTICS',
            'order-process-report*' => 'MDI_ORDER_ANALYTICS',
            'order-send-mail*' => 'MDI_ORDER_ANALYTICS',
            'other-item-reports/*' => 'MDI_OTHER_ITEM_REPORTS',
            'refinery-reports/*' => 'MDI_REFINERY_ANALYTICS',
            'remake-reports/*' => 'MDI_REPAIR_ANALYTICS',
            'staff-reports*' => 'MDI_STAFF_ANALYTICS',
            'term-summary*' => 'MDI_STAFF_ANALYTICS',
            'staff-transaction*' => 'MDI_STAFF_TRANSACTION',
            'staff-log-update*' => 'MDI_STAFF_LOG_UPDATE',
            'staff-leave-entry*' => 'MDI_STAFF_LEAVE_ENTRY',
            'staff-wgt-transaction*' => 'MDI_STAFF_WGT_TRANSACTION',
            'repair-complaints*' => 'MDI_REPAIR_COMPLAINTS',
            'remake-rcpt-memo-to-party*' => 'MDI_REPAIR_RECEIPT_MEMO_PARTY',
            'repair-return*' => 'MDI_REPAIR_RETURN',
        ];
    }
}
