from django.db import models


class Purchased(models.Model):
    pk = models.CompositePrimaryKey('slno', 'code')
    slno = models.DecimalField(max_digits=10, decimal_places=0)
    code = models.CharField(max_length=8)
    rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    lesswgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    lessperc = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    stwgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    stprice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    mud = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    fr = models.SmallIntegerField(blank=True, null=True)
    mark = models.CharField(max_length=1, blank=True, null=True)
    mcharge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    stktype = models.CharField(max_length=5, blank=True, null=True)
    bcode = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    iqtype = models.CharField(max_length=10, blank=True, null=True)
    stktouch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    touch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    dmdamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    smcharge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    mperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    dmdwgt = models.DecimalField(max_digits=9, decimal_places=3, blank=True, null=True)
    sstprice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    purity = models.CharField(max_length=10, blank=True, null=True)
    stkinnos = models.CharField(max_length=1, blank=True, null=True)
    rate2 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    batch = models.CharField(max_length=10, blank=True, null=True)
    wastage = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchased'


class PurchasedDmddet(models.Model):
    pk = models.CompositePrimaryKey('slno', 'code')
    slno = models.DecimalField(max_digits=10, decimal_places=0)
    code = models.CharField(max_length=10)
    prow = models.SmallIntegerField(blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    sttype = models.CharField(max_length=10, blank=True, null=True)
    stcolor = models.CharField(max_length=10, blank=True, null=True)
    stsize = models.CharField(max_length=10, blank=True, null=True)
    stcut = models.CharField(max_length=10, blank=True, null=True)
    stsettype = models.CharField(max_length=10, blank=True, null=True)
    pcs = models.SmallIntegerField(blank=True, null=True)
    carats = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    rate = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchased_dmddet'


class Purchasem(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    tdate = models.DateField(blank=True, null=True)
    ttime = models.TimeField(blank=True, null=True)
    billno = models.CharField(max_length=20, blank=True, null=True)
    docno = models.CharField(max_length=10, blank=True, null=True)
    suppcode = models.CharField(max_length=8, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    billamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    addamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.SmallIntegerField(blank=True, null=True)
    pr = models.CharField(max_length=1, blank=True, null=True)
    eamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    duedate = models.DateField(blank=True, null=True)
    pamtafter = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    control = models.SmallIntegerField(blank=True, null=True)
    rate = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    smcode = models.CharField(max_length=10, blank=True, null=True)
    round = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    netamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    taxamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ob = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    astamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ic = models.CharField(max_length=5, blank=True, null=True)
    alocamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    fr = models.CharField(max_length=1, blank=True, null=True)
    exchslno = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    taxexternal = models.CharField(max_length=1, blank=True, null=True)
    dmd = models.CharField(max_length=1, blank=True, null=True)
    bal = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    taxperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    cst = models.CharField(max_length=1, blank=True, null=True)
    tcsperc = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    tcsamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    billtype = models.CharField(max_length=5, blank=True, null=True)
    discperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    addr = models.CharField(max_length=60, blank=True, null=True)
    note = models.CharField(max_length=40, blank=True, null=True)
    chqbank = models.CharField(max_length=10, blank=True, null=True)
    chqamt = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    chqno = models.CharField(max_length=20, blank=True, null=True)
    chqdate = models.DateField(blank=True, null=True)
    chqpdc = models.CharField(max_length=1, blank=True, null=True)
    pan = models.CharField(max_length=20, blank=True, null=True)
    statecode = models.CharField(max_length=10, blank=True, null=True)
    sgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    igst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    mobile = models.CharField(max_length=20, blank=True, null=True)
    counter = models.CharField(max_length=10, blank=True, null=True)
    hmc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    taxonmconly = models.CharField(max_length=1, blank=True, null=True)
    hmcperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    tdsperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    tdsamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    cbcode = models.CharField(max_length=10, blank=True, null=True)
    tin = models.CharField(max_length=15, blank=True, null=True)
    rate24 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    rate18 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchasem'


class Purchaserd(models.Model):
    pk = models.CompositePrimaryKey('slno', 'code')
    slno = models.DecimalField(max_digits=10, decimal_places=0)
    code = models.CharField(max_length=10)
    rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    lesswgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    lessperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cost = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    stwgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    stprice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    mud = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    fr = models.SmallIntegerField(blank=True, null=True)
    mark = models.CharField(max_length=1, blank=True, null=True)
    mcharge = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    stktype = models.CharField(max_length=5, blank=True, null=True)
    stktouch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    bcode = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    iqtype = models.CharField(max_length=5, blank=True, null=True)
    touch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    dmdamt = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    dmdwgt = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    purity = models.CharField(max_length=6, blank=True, null=True)
    stkinnos = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchaserd'


class Purchaserm(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    tdate = models.DateField()
    ttime = models.TimeField(blank=True, null=True)
    billno = models.CharField(max_length=10, blank=True, null=True)
    docno = models.CharField(max_length=10, blank=True, null=True)
    suppcode = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    billamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ramt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    addamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    lessamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pr = models.CharField(max_length=1, blank=True, null=True)
    status = models.SmallIntegerField(blank=True, null=True)
    control = models.SmallIntegerField(blank=True, null=True)
    rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    smcode = models.CharField(max_length=10, blank=True, null=True)
    round = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    netamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ob = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    taxamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    astamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ic = models.CharField(max_length=5, blank=True, null=True)
    billdate = models.DateField(blank=True, null=True)
    sgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    igst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cst = models.CharField(max_length=1, blank=True, null=True)
    billtype = models.CharField(max_length=10, blank=True, null=True)
    taxexternal = models.CharField(max_length=1, blank=True, null=True)
    dmd = models.CharField(max_length=1, blank=True, null=True)
    taxperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchaserm'
