from django.db import models


class Salesd(models.Model):
    pk = models.CompositePrimaryKey('slno', 'code')
    slno = models.DecimalField(max_digits=10, decimal_places=0)
    code = models.CharField(max_length=8)
    qty = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    stonewgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    stoneprice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    lessperc = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    lesswgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    mcharge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    wastage = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    jcode = models.CharField(max_length=8, blank=True, null=True)
    kdm = models.CharField(max_length=1, blank=True, null=True)
    cost = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    jrate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    jva = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    bcode = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    dmdwgt = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    dmdunit = models.CharField(max_length=10, blank=True, null=True)
    dmdamt = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    dmdnos = models.IntegerField(blank=True, null=True)
    fr = models.SmallIntegerField(blank=True, null=True)
    rmno = models.CharField(max_length=10, blank=True, null=True)
    stkfd = models.CharField(max_length=1, blank=True, null=True)
    mark = models.CharField(max_length=1, blank=True, null=True)
    mca = models.SmallIntegerField(blank=True, null=True)
    stktype = models.CharField(max_length=5, blank=True, null=True)
    iqtype = models.CharField(max_length=10, blank=True, null=True)
    stktouch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    vaperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    model = models.CharField(max_length=15, blank=True, null=True)
    note = models.CharField(max_length=20, blank=True, null=True)
    huid = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'salesd'


class Salesm(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    billno = models.CharField(max_length=10, blank=True, null=True)
    tdate = models.DateField(blank=True, null=True)
    ttime = models.TimeField(blank=True, null=True)
    custcode = models.CharField(max_length=8, blank=True, null=True)
    custname = models.CharField(max_length=30, blank=True, null=True)
    billamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    eamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    staxperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    staxamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ramt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ramtafter = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    grate = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    srate = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    sr = models.CharField(max_length=1, blank=True, null=True)
    status = models.SmallIntegerField(blank=True, null=True)
    duedate = models.DateField(blank=True, null=True)
    control = models.SmallIntegerField(blank=True, null=True)
    sretamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    jrate = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    smcode = models.CharField(max_length=8, blank=True, null=True)
    alocamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ob = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    cocode = models.CharField(max_length=10, blank=True, null=True)
    round = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    opbill = models.SmallIntegerField(blank=True, null=True)
    prn = models.SmallIntegerField(blank=True, null=True)
    netamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    saletype = models.CharField(max_length=2, blank=True, null=True)
    advance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    marparty = models.CharField(max_length=1, blank=True, null=True)
    loan = models.CharField(max_length=1, blank=True, null=True)
    astamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    orderno = models.CharField(max_length=10, blank=True, null=True)
    counter = models.CharField(max_length=5, blank=True, null=True)
    taxdisc = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ic = models.CharField(max_length=5, blank=True, null=True)
    fr = models.CharField(max_length=1, blank=True, null=True)
    exchslno = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    retnslno = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    bal = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    tin = models.CharField(max_length=20, blank=True, null=True)
    astperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    dstatus = models.CharField(max_length=10, blank=True, null=True)
    secwgt = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    secnote = models.CharField(max_length=60, blank=True, null=True)
    tcsperc = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
    tcsamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    bultouch = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    tva = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    balwgt = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    billtype = models.CharField(max_length=5, blank=True, null=True)
    cbcode = models.CharField(max_length=10, blank=True, null=True)
    ograte = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    addr = models.CharField(max_length=60, blank=True, null=True)
    note = models.CharField(max_length=30, blank=True, null=True)
    bcharge = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    addbcharge = models.CharField(max_length=1, blank=True, null=True)
    ccamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    hmc = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    discperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    rddisc = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    showwgt = models.CharField(max_length=1, blank=True, null=True)
    ws = models.CharField(max_length=1, blank=True, null=True)
    gadvrate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    rcamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    thrate = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    cst = models.CharField(max_length=1, blank=True, null=True)
    printwanda = models.CharField(max_length=1, blank=True, null=True)
    mobno = models.CharField(max_length=25, blank=True, null=True)
    agcode = models.CharField(max_length=10, blank=True, null=True)
    schmamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    fancyamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    chqno = models.CharField(max_length=20, blank=True, null=True)
    chqdate = models.DateField(blank=True, null=True)
    chqamt = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    chqbank = models.CharField(max_length=10, blank=True, null=True)
    chqpdc = models.CharField(max_length=1, blank=True, null=True)
    placeos = models.CharField(max_length=40, blank=True, null=True)
    pan = models.CharField(max_length=20, blank=True, null=True)
    statecode = models.CharField(max_length=10, blank=True, null=True)
    sgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    igst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    redmpoints = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    bcperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    approvedby = models.CharField(max_length=10, blank=True, null=True)
    ccpdc = models.CharField(max_length=1, blank=True, null=True)
    vehno = models.CharField(max_length=15, blank=True, null=True)
    distance = models.IntegerField(blank=True, null=True)
    schmwgt = models.DecimalField(max_digits=9, decimal_places=3, blank=True, null=True)
    hmcperc = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    ppno = models.CharField(max_length=15, blank=True, null=True)
    nationality = models.CharField(max_length=20, blank=True, null=True)
    resident = models.CharField(max_length=2, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    rate18 = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'salesm'


class Salesrd(models.Model):
    pk = models.CompositePrimaryKey('slno', 'code')
    slno = models.DecimalField(max_digits=10, decimal_places=0)
    code = models.CharField(max_length=8)
    qty = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    rate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    stonewgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    stoneprice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    lessperc = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    lesswgt = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    mcharge = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    wastage = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    jcode = models.CharField(max_length=8, blank=True, null=True)
    kdm = models.CharField(max_length=1, blank=True, null=True)
    cost = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    fr = models.SmallIntegerField(blank=True, null=True)
    mark = models.CharField(max_length=1, blank=True, null=True)
    stktype = models.CharField(max_length=5, blank=True, null=True)
    iqtype = models.CharField(max_length=10, blank=True, null=True)
    stktouch = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    bcode = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    dmdwgt = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    vaperc = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    note = models.CharField(max_length=20, blank=True, null=True)
    huid = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'salesrd'


class Salesrm(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    billno = models.CharField(max_length=10, blank=True, null=True)
    tdate = models.DateField(blank=True, null=True)
    ttime = models.TimeField(blank=True, null=True)
    custcode = models.CharField(max_length=8, blank=True, null=True)
    custname = models.CharField(max_length=30, blank=True, null=True)
    billamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    eamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    staxperc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    staxamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    pamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pamtafter = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    grate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    srate = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    sr = models.CharField(max_length=1, blank=True, null=True)
    status = models.SmallIntegerField(blank=True, null=True)
    duedate = models.DateField(blank=True, null=True)
    control = models.SmallIntegerField(blank=True, null=True)
    smcode = models.CharField(max_length=10, blank=True, null=True)
    ob = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    round = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    netamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    astamt = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    ic = models.CharField(max_length=5, blank=True, null=True)
    fr = models.CharField(max_length=1, blank=True, null=True)
    retnslno = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    sbillno = models.CharField(max_length=15, blank=True, null=True)
    sgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cgst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    igst = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    cst = models.CharField(max_length=1, blank=True, null=True)
    billtype = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'salesrm'


class Wsaled(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    code = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    gr = models.CharField(max_length=1, blank=True, null=True)
    touchr = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    toucha = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    touchwgt = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    stonewgt = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    stoneprice = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    wastage = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    netwgt = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    mcharge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    sno = models.SmallIntegerField(blank=True, null=True)
    wgtal = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    cost = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    mark = models.CharField(max_length=1, blank=True, null=True)
    wastage2 = models.DecimalField(max_digits=8, decimal_places=3, blank=True, null=True)
    adjamt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wsaled'


class Wsalem(models.Model):
    slno = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
    tdate = models.DateField(blank=True, null=True)
    docno = models.CharField(max_length=10, blank=True, null=True)
    ccode = models.CharField(max_length=10, blank=True, null=True)
    cname = models.CharField(max_length=30, blank=True, null=True)
    amttr = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    amttg = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    amtpaid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    amtrcvd = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    control = models.SmallIntegerField(blank=True, null=True)
    grate = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    srate = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    pend = models.SmallIntegerField(blank=True, null=True)
    ttype = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wsalem'
